In [2]:
import sys
print(sys.version)

3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 10:07:17) [Clang 14.0.6 ]


In [4]:
import numpy as np
print(np.__version__)

1.26.4


In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a = np.arange(10)

In [12]:
a.mean()

4.5

In [14]:
a.sum()

45

In [16]:
a.min()

0

In [18]:
a.std()

2.8722813232690143

In [30]:
%timeit list(x*x for x in a)

864 ns ± 4.74 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [32]:
%timeit a*a

213 ns ± 2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [34]:
a * a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [36]:
[x*x for x in a]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [38]:
a = np.arange(20)

In [40]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [42]:
[x for x in a if x % 2 == 0]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [44]:
a[a % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [46]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [48]:
np.array(list(map(lambda x : x % 2 == 0, a)))

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [50]:
np2 = np.arange(20000)

In [52]:
%timeit [x for x in np2 if x %2 == 0]

1.22 ms ± 3.19 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [54]:
%time np2[np2 % 2 == 0]

CPU times: user 953 μs, sys: 927 μs, total: 1.88 ms
Wall time: 909 μs


array([    0,     2,     4, ..., 19994, 19996, 19998])

In [56]:
a[ (a > 15) | (a < 5)]

array([ 0,  1,  2,  3,  4, 16, 17, 18, 19])

In [58]:
npa = np.arange(25)

In [60]:
print(type(npa))

<class 'numpy.ndarray'>


In [62]:
npa.dtype

dtype('int64')

In [68]:
np.float32(npa)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.],
      dtype=float32)

In [66]:
np.float64(25)

25.0

In [70]:
np.array(range(20)).dtype

dtype('int64')

In [72]:
np.array([1.0,0,2,3]).dtype

dtype('float64')

In [74]:
np.array([True, 2, 2.0]).dtype

dtype('float64')

In [84]:
np.array([True, 2, 2.0], dtype='uint')

array([1, 2, 2], dtype=uint64)

In [86]:
npa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [90]:
npa.size

25

In [92]:
npa.shape

(25,)

In [94]:
npa.argmin()

0

In [96]:
npa.argmax()

24

In [98]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [100]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [104]:
np.linspace(0,10,11).astype('int')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
problem = np.array([0.])/np.array([0.])

/var/folders/y4/kt57fxd942z3zncr4rvv6t740000gn/T/ipykernel_7827/3991392179.py:1: RuntimeWarning: invalid value encountered in divide
  problem = np.array([0.])/np.array([0.])


In [108]:
problem

array([nan])

In [110]:
np.nan

nan

In [116]:
ar = np.linspace(0,10,11)
ar
ar[0] = np.nan
ar
ar.min(), ar.max(), ar.mean()

(nan, nan, nan)

In [118]:
import sys
print(sys.version)
import numpy as np
print(np.__version__)

3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 10:07:17) [Clang 14.0.6 ]
1.26.4


In [130]:
np.random.seed(20)
npa = np.random.random_integers(0,50,20)

/var/folders/y4/kt57fxd942z3zncr4rvv6t740000gn/T/ipykernel_7827/19388003.py:2: DeprecationWarning: This function is deprecated. Please call randint(0, 50 + 1) instead
  npa = np.random.random_integers(0,50,20)


In [132]:
npa

array([35, 26, 15, 31, 28, 26,  9, 20, 11, 22,  7, 34, 32, 40, 21, 26, 26,
       19, 16, 38])

In [134]:
npa * 2

array([70, 52, 30, 62, 56, 52, 18, 40, 22, 44, 14, 68, 64, 80, 42, 52, 52,
       38, 32, 76])

In [136]:
npa ** 2 ** 3

array([2251875390625,  208827064576,    2562890625,  852891037441,
        377801998336,  208827064576,      43046721,   25600000000,
           214358881,   54875873536,       5764801, 1785793904896,
       1099511627776, 6553600000000,   37822859361,  208827064576,
        208827064576,   16983563041,    4294967296, 4347792138496])

In [139]:
def transformation(val):
    return ((val * 2) - 1)

In [141]:
transformation(3)

5

In [143]:
transformation(2)

3

In [145]:
transformation(npa)

array([69, 51, 29, 61, 55, 51, 17, 39, 21, 43, 13, 67, 63, 79, 41, 51, 51,
       37, 31, 75])

In [147]:
transform_2 = np.vectorize(transformation)

In [149]:
transform_2(npa)

array([69, 51, 29, 61, 55, 51, 17, 39, 21, 43, 13, 67, 63, 79, 41, 51, 51,
       37, 31, 75])

In [151]:
%timeit [transformation(x) for x in npa]

2.02 μs ± 27.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [153]:
%timeit transform_2(npa)

3.25 μs ± 52.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [155]:
npa = np.arange(25)

In [157]:
npa2 = npa.reshape((5,5))

In [159]:
npa2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [165]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [167]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [171]:
np.zeros(npa2.shape)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [173]:
npa2.shape

(5, 5)

In [175]:
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [177]:
np.zeros((4,4,4,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

      

In [179]:
np.random.seed(10)

In [217]:
npa2 = np.random.random_integers(1,10,25).reshape(5,5)
npa2

/var/folders/y4/kt57fxd942z3zncr4rvv6t740000gn/T/ipykernel_7827/3543292635.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  npa2 = np.random.random_integers(1,10,25).reshape(5,5)


array([[ 5,  8,  9,  9,  3],
       [ 7,  3,  9,  9,  7],
       [ 7,  6,  7,  1,  1],
       [ 7, 10,  2,  9, 10],
       [ 2,  3,  9, 10, 10]])

In [183]:
npa3 = np.random.random_integers(1,10,25).reshape(5,5)
npa3

/var/folders/y4/kt57fxd942z3zncr4rvv6t740000gn/T/ipykernel_7827/2766334575.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  npa3 = np.random.random_integers(1,10,25).reshape(5,5)


array([[ 4, 10,  7, 10,  2],
       [10,  5,  3,  7,  8],
       [ 9,  9, 10,  3,  1],
       [ 7,  8,  9,  2,  8],
       [ 2,  5,  1,  9,  6]])

In [185]:
npa2 * 2

array([[20, 10,  2,  4, 20],
       [ 2,  4, 18, 20,  2],
       [18, 14, 10,  8,  2],
       [10, 14, 18,  4, 18],
       [10,  4,  8, 14, 12]])

In [189]:
(npa2 < npa3).sum()

12

In [191]:
npa2.min()

1

In [193]:
npa3.max(axis=1)

array([10, 10, 10,  9,  9])

In [195]:
npa3.min(axis=0)

array([2, 5, 1, 2, 1])

In [201]:
npa2.transpose() == npa2.T

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [199]:
npa2.T

array([[10,  1,  9,  5,  5],
       [ 5,  2,  7,  7,  2],
       [ 1,  9,  5,  9,  4],
       [ 2, 10,  4,  2,  7],
       [10,  1,  1,  9,  6]])

In [203]:
npa2, npa3

(array([[10,  5,  1,  2, 10],
        [ 1,  2,  9, 10,  1],
        [ 9,  7,  5,  4,  1],
        [ 5,  7,  9,  2,  9],
        [ 5,  2,  4,  7,  6]]),
 array([[ 4, 10,  7, 10,  2],
        [10,  5,  3,  7,  8],
        [ 9,  9, 10,  3,  1],
        [ 7,  8,  9,  2,  8],
        [ 2,  5,  1,  9,  6]]))

In [205]:
npa2 * npa3

array([[40, 50,  7, 20, 20],
       [10, 10, 27, 70,  8],
       [81, 63, 50, 12,  1],
       [35, 56, 81,  4, 72],
       [10, 10,  4, 63, 36]])

In [219]:
np2 = npa2.flatten()
np2

array([ 5,  8,  9,  9,  3,  7,  3,  9,  9,  7,  7,  6,  7,  1,  1,  7, 10,
        2,  9, 10,  2,  3,  9, 10, 10])

In [221]:
np2[0] = 25

In [223]:
npa2

array([[ 5,  8,  9,  9,  3],
       [ 7,  3,  9,  9,  7],
       [ 7,  6,  7,  1,  1],
       [ 7, 10,  2,  9, 10],
       [ 2,  3,  9, 10, 10]])

np2

In [227]:
raveled = npa2.ravel()

In [229]:
raveled

array([ 5,  8,  9,  9,  3,  7,  3,  9,  9,  7,  7,  6,  7,  1,  1,  7, 10,
        2,  9, 10,  2,  3,  9, 10, 10])

In [231]:
raveled[0] = 25
npa2

array([[25,  8,  9,  9,  3],
       [ 7,  3,  9,  9,  7],
       [ 7,  6,  7,  1,  1],
       [ 7, 10,  2,  9, 10],
       [ 2,  3,  9, 10, 10]])

In [233]:
npa2.cumsum()

array([ 25,  33,  42,  51,  54,  61,  64,  73,  82,  89,  96, 102, 109,
       110, 111, 118, 128, 130, 139, 149, 151, 154, 163, 173, 183])

In [235]:
npa2.cumprod()

array([                  25,                  200,                 1800,
                      16200,                48600,               340200,
                    1020600,              9185400,             82668600,
                  578680200,           4050761400,          24304568400,
               170131978800,         170131978800,         170131978800,
              1190923851600,       11909238516000,       23818477032000,
            214366293288000,     2143662932880000,     4287325865760000,
          12861977597280000,   115757798375520000,  1157577983755200000,
       -6870964236157551616])

## Query, Slicing, Combining Arrays

In [240]:
np.random.seed(10)
ar = np.arange(12)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [244]:
ar2 = np.random.random_integers(12, size=12).reshape((3,4))
ar2

/var/folders/y4/kt57fxd942z3zncr4rvv6t740000gn/T/ipykernel_7827/1136468151.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 12 + 1) instead
  ar2 = np.random.random_integers(12, size=12).reshape((3,4))


array([[11,  9,  7,  5],
       [ 4,  1,  5, 12],
       [ 7,  9, 12, 11]])

In [246]:
ar[0]

0

In [248]:
ar[5]

5

In [250]:
ar[5:]

array([ 5,  6,  7,  8,  9, 10, 11])

In [252]:
ar[:5]

array([0, 1, 2, 3, 4])

In [254]:
ar[2:8:2]

array([2, 4, 6])

In [256]:
ar[:-1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [258]:
ar[:-5]

array([0, 1, 2, 3, 4, 5, 6])

In [260]:
ar[-1:-8:-2]

array([11,  9,  7,  5])

In [262]:
ar2

array([[11,  9,  7,  5],
       [ 4,  1,  5, 12],
       [ 7,  9, 12, 11]])

In [264]:
ar2[:,1:3]

array([[ 9,  7],
       [ 1,  5],
       [ 9, 12]])

In [266]:
ar2[1:3, :]

array([[ 4,  1,  5, 12],
       [ 7,  9, 12, 11]])

In [272]:
ar2[1:3:2, 1:4:2]

array([[ 1, 12]])

In [274]:
ar2[::2, ::2]

array([[11,  7],
       [ 7, 12]])

In [276]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [278]:
ar2

array([[11,  9,  7,  5],
       [ 4,  1,  5, 12],
       [ 7,  9, 12, 11]])

In [280]:
ar2.flatten()

array([11,  9,  7,  5,  4,  1,  5, 12,  7,  9, 12, 11])

In [282]:
np.vstack([ar,ar2.flatten()])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [11,  9,  7,  5,  4,  1,  5, 12,  7,  9, 12, 11]])

In [284]:
ar2

array([[11,  9,  7,  5],
       [ 4,  1,  5, 12],
       [ 7,  9, 12, 11]])

In [286]:
ar.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [288]:
np.vstack((ar.reshape((3,4)), ar2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [11,  9,  7,  5],
       [ 4,  1,  5, 12],
       [ 7,  9, 12, 11]])

In [294]:
np.hstack((ar, ar2.flatten(), ar))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 11,  9,  7,  5,  4,
        1,  5, 12,  7,  9, 12, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11])

In [296]:
np.hstack((ar.reshape((3,4)), ar2))

array([[ 0,  1,  2,  3, 11,  9,  7,  5],
       [ 4,  5,  6,  7,  4,  1,  5, 12],
       [ 8,  9, 10, 11,  7,  9, 12, 11]])

In [298]:
(ar for x in range(10))

<generator object <genexpr> at 0x14dfabb80>

In [302]:
np.vstack([ar for x in range(10)])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [304]:
np.concatenate((ar, ar2.flatten()))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 11,  9,  7,  5,  4,
        1,  5, 12,  7,  9, 12, 11])

In [306]:
np.concatenate(([ar], [ar2.flatten()]), axis=0)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [11,  9,  7,  5,  4,  1,  5, 12,  7,  9, 12, 11]])

In [308]:
np.concatenate(([ar], [ar2.flatten()]))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [11,  9,  7,  5,  4,  1,  5, 12,  7,  9, 12, 11]])

In [310]:
np.concatenate((ar2, ar2))

array([[11,  9,  7,  5],
       [ 4,  1,  5, 12],
       [ 7,  9, 12, 11],
       [11,  9,  7,  5],
       [ 4,  1,  5, 12],
       [ 7,  9, 12, 11]])

In [312]:
np.concatenate((ar2,ar2), axis=1)

array([[11,  9,  7,  5, 11,  9,  7,  5],
       [ 4,  1,  5, 12,  4,  1,  5, 12],
       [ 7,  9, 12, 11,  7,  9, 12, 11]])

In [314]:
np.dstack((ar2,ar2))

array([[[11, 11],
        [ 9,  9],
        [ 7,  7],
        [ 5,  5]],

       [[ 4,  4],
        [ 1,  1],
        [ 5,  5],
        [12, 12]],

       [[ 7,  7],
        [ 9,  9],
        [12, 12],
        [11, 11]]])

In [316]:
ar3 = np.dstack((ar2,ar2))
ar3

array([[[11, 11],
        [ 9,  9],
        [ 7,  7],
        [ 5,  5]],

       [[ 4,  4],
        [ 1,  1],
        [ 5,  5],
        [12, 12]],

       [[ 7,  7],
        [ 9,  9],
        [12, 12],
        [11, 11]]])

In [322]:
ar21, ar22 = np.dsplit(ar3,2)
ar21.reshape(3,4)

array([[11,  9,  7,  5],
       [ 4,  1,  5, 12],
       [ 7,  9, 12, 11]])

In [324]:
np.dsplit(ar3,2)

[array([[[11],
         [ 9],
         [ 7],
         [ 5]],
 
        [[ 4],
         [ 1],
         [ 5],
         [12]],
 
        [[ 7],
         [ 9],
         [12],
         [11]]]),
 array([[[11],
         [ 9],
         [ 7],
         [ 5]],
 
        [[ 4],
         [ 1],
         [ 5],
         [12]],
 
        [[ 7],
         [ 9],
         [12],
         [11]]])]

In [326]:
np.squeeze(np.dsplit(ar3,2)[0])

array([[11,  9,  7,  5],
       [ 4,  1,  5, 12],
       [ 7,  9, 12, 11]])

In [328]:
ar2

array([[11,  9,  7,  5],
       [ 4,  1,  5, 12],
       [ 7,  9, 12, 11]])

In [330]:
np.hsplit(ar2, 2)

[array([[11,  9],
        [ 4,  1],
        [ 7,  9]]),
 array([[ 7,  5],
        [ 5, 12],
        [12, 11]])]

In [336]:
np.hsplit(ar2, 2)

[array([[11,  9],
        [ 4,  1],
        [ 7,  9]]),
 array([[ 7,  5],
        [ 5, 12],
        [12, 11]])]

In [342]:
np.vsplit(ar2.T, 4)

[array([[11,  4,  7]]),
 array([[9, 1, 9]]),
 array([[ 7,  5, 12]]),
 array([[ 5, 12, 11]])]

In [340]:
ar2.reshape((4,3))

array([[11,  9,  7],
       [ 5,  4,  1],
       [ 5, 12,  7],
       [ 9, 12, 11]])

## Matrix Operations

In [347]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
b = np.array([
    [1,1],
    [0,1],
    [2,2]
])

In [349]:
a.shape, b.shape

((2, 3), (3, 2))

In [351]:
a.dot(b)

array([[ 7,  9],
       [16, 21]])

In [353]:
b.dot(a)

array([[ 5,  7,  9],
       [ 4,  5,  6],
       [10, 14, 18]])

In [355]:
a @ b

array([[ 7,  9],
       [16, 21]])

In [357]:
b @ a

array([[ 5,  7,  9],
       [ 4,  5,  6],
       [10, 14, 18]])

In [359]:
v = np.array([1,2])

In [361]:
v

array([1, 2])

In [363]:
v.shape

(2,)

In [371]:
v_row = v.reshape(1,-1)

In [373]:
v_row

array([[1, 2]])

In [379]:
v_col = v.reshape(-1,1)
v_col

array([[1],
       [2]])

In [381]:
b.shape, v_col.shape

((3, 2), (2, 1))

In [383]:
b @ v_col

array([[3],
       [2],
       [6]])

In [385]:
b @ v

array([3, 2, 6])

In [387]:
b.shape, v.shape

((3, 2), (2,))