In [2]:
import sys
print(sys.version)

3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 10:07:17) [Clang 14.0.6 ]


In [4]:
import numpy as np
print(np.__version__)

1.26.4


In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a = np.arange(10)

In [12]:
a.mean()

4.5

In [14]:
a.sum()

45

In [16]:
a.min()

0

In [18]:
a.std()

2.8722813232690143

In [30]:
%timeit list(x*x for x in a)

864 ns ± 4.74 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [32]:
%timeit a*a

213 ns ± 2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [34]:
a * a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [36]:
[x*x for x in a]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [38]:
a = np.arange(20)

In [40]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [42]:
[x for x in a if x % 2 == 0]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [44]:
a[a % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [46]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [48]:
np.array(list(map(lambda x : x % 2 == 0, a)))

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [50]:
np2 = np.arange(20000)

In [52]:
%timeit [x for x in np2 if x %2 == 0]

1.22 ms ± 3.19 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [54]:
%time np2[np2 % 2 == 0]

CPU times: user 953 μs, sys: 927 μs, total: 1.88 ms
Wall time: 909 μs


array([    0,     2,     4, ..., 19994, 19996, 19998])

In [56]:
a[ (a > 15) | (a < 5)]

array([ 0,  1,  2,  3,  4, 16, 17, 18, 19])

In [58]:
npa = np.arange(25)

In [60]:
print(type(npa))

<class 'numpy.ndarray'>


In [62]:
npa.dtype

dtype('int64')

In [68]:
np.float32(npa)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.],
      dtype=float32)

In [66]:
np.float64(25)

25.0

In [70]:
np.array(range(20)).dtype

dtype('int64')

In [72]:
np.array([1.0,0,2,3]).dtype

dtype('float64')

In [74]:
np.array([True, 2, 2.0]).dtype

dtype('float64')

In [84]:
np.array([True, 2, 2.0], dtype='uint')

array([1, 2, 2], dtype=uint64)

In [86]:
npa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [90]:
npa.size

25

In [92]:
npa.shape

(25,)

In [94]:
npa.argmin()

0

In [96]:
npa.argmax()

24

In [98]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [100]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [104]:
np.linspace(0,10,11).astype('int')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
problem = np.array([0.])/np.array([0.])

/var/folders/y4/kt57fxd942z3zncr4rvv6t740000gn/T/ipykernel_7827/3991392179.py:1: RuntimeWarning: invalid value encountered in divide
  problem = np.array([0.])/np.array([0.])


In [108]:
problem

array([nan])

In [110]:
np.nan

nan

In [116]:
ar = np.linspace(0,10,11)
ar
ar[0] = np.nan
ar
ar.min(), ar.max(), ar.mean()

(nan, nan, nan)